Add dropbox url explanation
ejdataeditor/ejdataeditor.github.io pull request #4
Opened 2024-10-27 10:34 UTC by wiktorze

2024-10-27 14:35 UTC, floswald requested changes
thanks so much!

2024-10-27 14:35 UTC, floswald commented on replicator-resources.qmd
> +https://www.dropbox.com/scl/fo/gumryf1zs8lwk5zq5udo7/ABrnRWk5w859IIibD-_QM1Q/Szumilo-20230708-R1?*dl=1*&preview=Niko+Szumilo+-+MS20230708-replication.zip&rlkey=ei2aozcysqcchaoiwwanjcg4s&subfolder_nav
let's convert this into
```
https://www.dropbox.com/scl/fo/gumryf1zs8lwk5zq5udo7/ABrnRWk5w859IIib/Author-YYYYMMDD-R1?*dl=1*
```

I garbled up the URL and deleted the rest of the parameters which we don't need.

2024-10-27 14:35 UTC, floswald commented on replicator-resources.qmd
> +rm 'old_file_name'
you don't need the `rm`

2024-10-27 14:35 UTC, floswald commented on replicator-resources.qmd
> +If the file is very large, move it to the large file storage that you can create in the 'Project Configuration' tab.
this part is actually pretty hard to read what I did here. could you maybe change this bit into a more readable example please?  not much to change but remove the `(base)` stuff and shorten the super long name a bit (maybe refer to tab completion again - people are not suppose to type that thing...) thank

2024-11-07 13:54 UTC, ejdataeditor commented
thanks a lot!

2024-11-07 13:54 UTC, merged